# SPDX-License-Identifier: MIT
CONFIG_APEX_G4B_RADIO_PAIRING=y
CONFIG_APEX_G4B_DONGLE_RADIO=y
CONFIG_APEX_G4B_RADIO_PROBE=y
CONFIG_APEX_G4B_RADIO_INPUT=y
CONFIG_APEX_RADIO_TEST_CHANNEL=74
CONFIG_APEX_RADIO_HOPPING=y
CONFIG_ZMK_HID_INDICATORS=y
