# SPDX-License-Identifier: MIT
# ATTENDED TEST ONLY: deliberately faults after appending the boot-pending tally
# byte. The v2 bootloader must restore an already staged known-good image B
# after three failed boots. Never merge this into g4b_usb.conf.
CONFIG_APEX_G4B_AB_CRASHTEST=y
